feat: add variable to quickget for host, guest and qemu architectures

diff --git a/quickget b/quickget
--- a/quickget
+++ b/quickget
@@ -3390,6 +3390,22 @@ if ((BASH_VERSINFO[0] < 4)); then
     exit 1
 fi
 
+# ARCH_GUEST is the common string used in the URL
+# ARCH_QEMU is the suffix used by to determine the qemu-system-<arch> to use and what is written into the VM config
+ARCH_HOST=$(uname -m)
+case ${ARCH_HOST} in
+    amd64|x86_64)
+        ARCH_GUEST="amd64"
+        ARCH_QEMU="x86_64";;
+    arm64|armv8*|aarch64)
+        ARCH_GUEST="aarch64"
+        ARCH_QEMU="aarch64";;
+    i386|i686)
+        ARCH_GUEST="i686"
+        ARCH_QEMU="i386";;
+    *) echo "ERROR! This host is ${ARCH_HOST} and not currently supported."
+       exit 1;;
+esac
 I18NS=()
 OPERATION=""
 CURL=$(command -v curl)
